export const idleAnimation = {
  v: "5.5.2",
  fr: 30,
  ip: 0,
  op: 60,
  w: 200,
  h: 200,
  nm: "Idle",
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: "Shape Layer 1",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [100, 100, 0], ix: 2 },
        a: { a: 0, k: [0, 0, 0], ix: 1 },
        s: {
          a: 1,
          k: [
            { i: { x: [0.833], y: [0.833] }, o: { x: [0.167], y: [0.167] }, t: 0, s: [100, 100, 100] },
            { i: { x: [0.833], y: [0.833] }, o: { x: [0.167], y: [0.167] }, t: 30, s: [110, 110, 100] },
            { t: 60, s: [100, 100, 100] },
          ],
          ix: 6,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: "el",
          d: 1,
          p: { a: 0, k: [0, 0], ix: 3 },
          s: { a: 0, k: [100, 100], ix: 4 },
          nm: "Ellipse Path 1",
          mn: "ADBE Vector Shape - Ellipse",
          hd: false,
        },
        {
          ty: "fl",
          c: { a: 0, k: [0.1, 0.6, 0.9, 1], ix: 4 },
          o: { a: 0, k: 100, ix: 5 },
          r: 1,
          bm: 0,
          nm: "Fill 1",
          mn: "ADBE Vector Graphic - Fill",
          hd: false,
        },
      ],
      ip: 0,
      op: 60,
      st: 0,
      bm: 0,
    },
  ],
};

export const talkingAnimation = {
  v: "5.5.2",
  fr: 30,
  ip: 0,
  op: 20,
  w: 200,
  h: 200,
  nm: "Talking",
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: "Shape Layer 1",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [100, 100, 0], ix: 2 },
        a: { a: 0, k: [0, 0, 0], ix: 1 },
        s: {
          a: 1,
          k: [
            { i: { x: [0.833], y: [0.833] }, o: { x: [0.167], y: [0.167] }, t: 0, s: [100, 100, 100] },
            { i: { x: [0.833], y: [0.833] }, o: { x: [0.167], y: [0.167] }, t: 10, s: [130, 80, 100] },
            { t: 20, s: [100, 100, 100] },
          ],
          ix: 6,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: "el",
          d: 1,
          p: { a: 0, k: [0, 0], ix: 3 },
          s: { a: 0, k: [100, 100], ix: 4 },
          nm: "Ellipse Path 1",
          mn: "ADBE Vector Shape - Ellipse",
          hd: false,
        },
        {
          ty: "fl",
          c: { a: 0, k: [0.2, 0.8, 0.4, 1], ix: 4 },
          o: { a: 0, k: 100, ix: 5 },
          r: 1,
          bm: 0,
          nm: "Fill 1",
          mn: "ADBE Vector Graphic - Fill",
          hd: false,
        },
      ],
      ip: 0,
      op: 20,
      st: 0,
      bm: 0,
    },
  ],
};

export const thinkingAnimation = {
  v: "5.5.2",
  fr: 30,
  ip: 0,
  op: 60,
  w: 200,
  h: 200,
  nm: "Thinking",
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: "Shape Layer 1",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: {
          a: 1,
          k: [
            { i: { x: [0.833], y: [0.833] }, o: { x: [0.167], y: [0.167] }, t: 0, s: [0] },
            { t: 60, s: [360] },
          ],
          ix: 10,
        },
        p: { a: 0, k: [100, 100, 0], ix: 2 },
        a: { a: 0, k: [0, 0, 0], ix: 1 },
        s: { a: 0, k: [100, 100, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: "el",
          d: 1,
          p: { a: 0, k: [0, 20], ix: 3 },
          s: { a: 0, k: [20, 20], ix: 4 },
          nm: "Dot 1",
          mn: "ADBE Vector Shape - Ellipse",
          hd: false,
        },
        {
          ty: "el",
          d: 1,
          p: { a: 0, k: [20, -10], ix: 3 },
          s: { a: 0, k: [20, 20], ix: 4 },
          nm: "Dot 2",
          mn: "ADBE Vector Shape - Ellipse",
          hd: false,
        },
        {
          ty: "el",
          d: 1,
          p: { a: 0, k: [-20, -10], ix: 3 },
          s: { a: 0, k: [20, 20], ix: 4 },
          nm: "Dot 3",
          mn: "ADBE Vector Shape - Ellipse",
          hd: false,
        },
        {
          ty: "fl",
          c: { a: 0, k: [0.9, 0.5, 0.1, 1], ix: 4 },
          o: { a: 0, k: 100, ix: 5 },
          r: 1,
          bm: 0,
          nm: "Fill 1",
          mn: "ADBE Vector Graphic - Fill",
          hd: false,
        },
      ],
      ip: 0,
      op: 60,
      st: 0,
      bm: 0,
    },
  ],
};
